name: marp-to-pages
concurrency: marp-to-pages

on:
  push:
    branches: ["master"]

jobs:
  build-marp:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure build dir exists
        run: mkdir -p dist-slide

      - name: Marp Build (HTML)
        uses: docker://marpteam/marp-cli:v3.3.0
        with:
          args: slide.md --theme academic-erbase.css -o dist-slide/xxx-slide.html
        env:
          MARP_USER: root:root
          LANG: "pt_BR.UTF-8"

      - name: Marp Build (PDF)
        uses: docker://marpteam/marp-cli:v3.3.0
        with:
          args: slide.md --theme academic-erbase.css --allow-local-files -o dist-slide/xxx-slide.pdf
        env:
          MARP_USER: root:root
          LANG: "pt_BR.UTF-8"

      - name: Marp Build (PPTX)
        uses: docker://marpteam/marp-cli:v3.3.0
        with:
          args: slide.md --theme academic-erbase.css --allow-local-files -o dist-slide/xxx-slide.pptx
        env:
          MARP_USER: root:root
          LANG: "pt_BR.UTF-8"

      - name: Archive marp artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-marp
          path: dist-slide
          retention-days: 90

  build-page:
    needs: [build-marp]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Download slide artifact
        uses: actions/download-artifact@v3
        with:
          name: dist-marp

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: reinanhs/limarka-render-html:v0.1.3
          options: |
            -v ${{ github.workspace }}:/var/www/html/data
            -e APP_BASE_URL=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
            -e GITHUB_REPOSITORY_OWNER=${{ github.repository_owner }}
            -e GITHUB_REPOSITORY=${{ github.event.repository.name }}
          run: |
            cd /var/www/html
            cp data/configuracao.yaml .
            mkdir -p source/assets/files/
            cp data/xxx-* source/assets/files/
            cp data/pages/*.md source/_pages
            vendor/bin/jigsaw build
            mv build_local/assets/files/xxx-slide/index.html build_local/slide.html
            rm build_local/assets/files/xxx-slide
            mkdir -p data/build
            cp build_local/* data/build -r
      - name: Altera√ß√£o do nome dos bot√µes
        run: |
          ls -al build
          sudo sed -i '0,/Visualizar PDF/s//Visualizar Slide/' build/index.html
          sudo sed -i "s|location.href = 'https://ReinanHS.github.io/marp-erbase-presentation/assets/files/slide.pdf'|location.href = 'https://reinanhs.github.io/marp-erbase-presentation/slide'|" build/index.html
      
      - name: Archive limarka artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-page
          path: build
          retention-days: 1
  deploy:
    needs: build-page
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v3
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build-page
          path: build
      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.